{ config, lib, ... }:
# FIXME: Strongly opinionated and uses redundant options to set things which can be changed with normal NixOS config fucntions. This should be global, preferably at the user level, or at the host level if not possible.
let
  cfg = config.theorem.nixos.base.locale;
in
{
  options.theorem.nixos.base.locale = {
    enable = lib.mkEnableOption "base locale configuration";

    timeZone = lib.mkOption {
      type = lib.types.str;
      default = "Europe/Rome";
      description = "IANA time zone for the host.";
    };

    defaultLocale = lib.mkOption {
      type = lib.types.str;
      default = "en_GB.UTF-8";
      description = "Default system locale.";
    };

    supportedLocales = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "en_GB.UTF-8/UTF-8"
        "en_US.UTF-8/UTF-8"
        "it_IT.UTF-8/UTF-8"
      ];
      description = "Locales generated by the system.";
    };

    extraLocaleSettings = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        LC_MONETARY = "it_IT.UTF-8";
        LC_PAPER = "it_IT.UTF-8";
        LC_MEASUREMENT = "it_IT.UTF-8";
      };
      description = "Additional LC_* locale settings for regional calibration.";
    };
  };

  config = lib.mkIf cfg.enable {
    time.timeZone = cfg.timeZone;

    i18n.defaultLocale = cfg.defaultLocale;

    i18n.supportedLocales = cfg.supportedLocales;

    i18n.extraLocaleSettings = cfg.extraLocaleSettings;
  };
}
