{ config, lib, ... }:
let
  cfg = config.theorem.nixos.base.locale;
in
{
  options.theorem.nixos.base.locale = {
    enable = lib.mkEnableOption "base locale configuration";

    timeZone = lib.mkOption {
      type = lib.types.str;
      default = "UTC";
      description = ''
        IANA time zone for the host. Reusable profiles keep this neutral;
        hosts should declare their local clock posture explicitly.
      '';
    };

    defaultLocale = lib.mkOption {
      type = lib.types.str;
      default = "en_US.UTF-8";
      description = ''
        Default system locale. Host or user profiles should override this when
        the operator needs regional spelling, formats, or collation.
      '';
    };

    supportedLocales = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "en_US.UTF-8/UTF-8"
      ];
      description = ''
        Locales generated by the system. Keep the reusable default small; hosts
        can add the operator and recovery locales they actually need.
      '';
    };

    extraLocaleSettings = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Additional LC_* locale settings for regional calibration.";
    };
  };

  config = lib.mkIf cfg.enable {
    time.timeZone = cfg.timeZone;

    i18n.defaultLocale = cfg.defaultLocale;

    i18n.supportedLocales = cfg.supportedLocales;

    i18n.extraLocaleSettings = cfg.extraLocaleSettings;
  };
}
