# Replace this placeholder with the public key from:
#   age-keygen -y /nix/persist/secrets/sops/age/keys.txt
keys:
  - &solanine age16penp9h358n9nyk06lajtdtncks7tqd8ww4u0zuelmkzc9jfg5cszyq8em
  - &firelink age142lwvvtlu8v566ug6seyayesaf7dmreqjnpa5muwxg7cj9j8230qqq0px5

creation_rules:
  - path_regex: secrets/solanine\.yaml$
    key_groups:
      - age:
          - *solanine
  - path_regex: secrets/firelink\.yaml$
    key_groups:
      - age:
          - *firelink
  - path_regex: secrets/ssh-admin\.yaml$
    key_groups:
      - age:
          - *solanine
          - *firelink
  - path_regex: secrets/ssh-vicky\.yaml$
    key_groups:
      - age:
          - *solanine
          - *firelink
  - path_regex: secrets/ssh-mattia\.yaml$
    key_groups:
      - age:
          - *firelink
