# TODO: Remember this message, but don't use it as gospel.
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # TODO: A lot of stuff here should be host-based, but the disks could probably be put in other modules. See below.
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    # Forces the driver to ignore the integrated display block entirely
    "amdgpu.sg_display=0"

    # Disables Panel Self Refresh (PSR) which causes sudden frame-drop freezes on Wayland
    "amdgpu.dcdebugmask=0x10"
  ];

  # TODO: Same, per host config.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
